name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show current directory and files
        run: |
          pwd
          ls -la

      - name: Debug environment variables
        run: |
          echo "EC2_USER=${{ secrets.EC2_USER }}"
          echo "EC2_HOST=${{ secrets.EC2_HOST }}"

      - name: Run a simple command
        run: echo "Deploy started"
