name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          remote-user: ubuntu
          server-ip: ${{ secrets.EC2_SERVER_IP }}
          remote-path: /home/ubuntu/js.practice
          local-path: .
          pre-deploy-command: |
            cd /home/ubuntu/js.practice
            git pull origin main
          post-deploy-command: |
            cd /home/ubuntu/js.practice
            ./restart-server.sh
