name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH using appleboy/ssh-action
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}        
          username: ${{ secrets.EC2_USER }}   
          key: ${{ secrets.SSH_PRIVATE_KEY }}                              
          script: |
            pwd
            whoami
            cd js.practice
            git pull origin main 
            npm install 
            pm2 restart server.js
