name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ ! -d "js.practice" ]; then
              git clone https://github.com/Abdullahafxal/js.practice.git
            else
              cd js.practice && git pull origin main
            fi

            cd js.practice

            # If your project uses Node.js
            if [ -f "package.json" ]; then
              npm install
              pm2 restart server.js || pm2 start server.js --name jspractice
            fi
