name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    -- name: Set up Node.js
        uses: actions/setup-node@v3
        with:
           node-version: '16'

      - name: Install dependencies
        run: npm install      

      - name: Run tests
        run: npm test
          script: |  
            echo "Connected successfully"
            cd /home/hajra/projects/js.practice  || exit 1
            git pull origin main
            npm ci
            pm2 restart all  
        
         
        
        
          