name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.Remote_Host }}
          username: linuxuserver.io
          key: ${{ env.Private_Key }}
          port: 22
          script: |
            cd /home/hajra/projects/js.practice  || exit 1
            git pull origin main
            npm ci
            pm2 restart all  
        
         
        
        
          