name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy via SSH to EC2
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          TARGET: /home/ubuntu/js.practice
          SOURCE: ./
          REMOTE_PORT: 22
          ARGS: -rlgoDzvc -i
          SSH_CMD_ARGS: -o StrictHostKeyChecking=no
